#cloud-config
runcmd:
  - export DB_USERNAME=csye6225fall2020
  - export DB_PASSWORD=Test@1234
  - export DB_HOST=${rds_hostname}
  - export s3_bucket_name=webapp.trivedh.audurthi
  - export DB_PORT=3306
  - export DATABASE="csye6225-f20"